### DISCUSSION TITLE
Listing Custom Task

### DISCUSSION THREAD

**Discussion by vdemeester** [tektoncd/community#667] [Ideas]
As Custom Task will go [beta](https://github.com/tektoncd/pipeline/issues/4313) (meaning relatively stable and **enabled by default**), it would be interesting to have a way to register, index, list and read about existing Custom Task. Today most of the Custom Task are written and live in [`tektoncd/experimental`](https://github.com/tektoncd/experimental) but that's probably going to change as anybody will be able to provide Custom Task.

A few existing Custom Task that lives outside of the `tektoncd` org today:
- [automatiko-approval-task](https://github.com/automatiko-io/automatiko-approval-task)
- [tekton-tasgroup-task](https://github.com/vdemeester/tekton-task-group)
- [tekton-ocipipeline-task](https://github.com/vdemeester/tekton-oci-pipeline)

Ideally, it should be possible to list them from the [hub](https://hub.tekton.dev), but it comes with the question on how / where do we want to "register" known / public Custom Task out there.

/cc @tektoncd/hub-maintainers @tektoncd/core-maintainers @tektoncd/experimental-maintainers

**Comment by lbernick** [comment]
relevant to #523

**Comment by jerop** [comment]
had a discussion with @vinamra28 about this - we could add a `customtasks.yaml` to list `Custom Tasks` surfaced in the Hub, in the same way [config.yaml][config] is used for Catalogs. Each entry will provide a `Custom Task` in the Hub, for example:

```yaml
custom-tasks:
  
  - name: approval
    org: automatiko-io
    type: community
    provider: github
    url: https://github.com/automatiko-io/automatiko-approval-task
    revision: main
    categories: 
      - Deployment
      - Integration & Delivery
  
  - name: task-group
    org: openshift-pipelines
    type: community
    provider: github
    url: github.com/openshift-pipelines/tekton-task-group
    revision: main
    categories:
      - Openshift
      
  - name: cel
    org: tektoncd
    type: official
    provider: github
    url: github.com/tektoncd/cel
    revision: main
```

we'd also require that the listed `Custom Task` has a `README.md` documenting its functionality, including installation instructions, which will be surfaced in the Hub 

what do you think @vdemeester @lbernick?

[config]: https://github.com/tektoncd/hub/blob/0ba02511db7a06aef54e2257bf2540be85b53f45/config.yaml

**Reply by vinamra28** [reply]
Adding to what @jerop said, each custom task should have metadata, which probably we can keep in an external file (eg metadata.yaml) and should be having following contents:
```yaml
description:
releaseYaml:
version:
tags:
categories:
platform:
contributor: tekton/openshift/etc
```
(This is just thinking at high level)
