### ISSUE TITLE
Support setting default PipelineRun Workspace Binding

### ISSUE THREAD

**Issue by fayfaychan** [tektoncd/community#1108]
### Feature request

Tekton currently supports default TaskRun workspace binding: https://tekton.dev/docs/pipelines/workspaces/#setting-a-default-taskrun-workspace-binding

Can we do the same for PipelineRun for workspaces defined in the pipelinespec? 

### Use case

If a user has a pipeline as below, the organization can set a default workspace configuration and user don't need to specify the same on the Run. 

```
# pipeline.yaml
metadata:
  name: pipeline
spec:
  workspaces:
    - name: pipeline-ws1
  tasks:
    - name: use-ws-again
      taskRef:
        name: commit # commit expects a workspace named "src"
      workspaces:
        - name: src
          workspace: pipeline-ws1
```

```
# pipelinerun.yaml
spec:
  pipelineRef:
    name: pipeline
  # workspaces:
  #  - name: unusedworkspace
  #    persistentVolumeClaim:
  #      claimName: mypvc
```
