### ISSUE TITLE
Project proposal: Catalog CR (and cli ext.) in experimental

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/community#53]
Based on the [Tekton catalog integration proposal](https://docs.google.com/document/d/1O8VHZ-7tNuuRjPNjPfdo8bD--WDrkcz-lbtJ3P8Wugs/edit#heading=h.iyqzt1brkg3o), 

This folder/repository would host [Catalog resource](https://docs.google.com/document/d/1O8VHZ-7tNuuRjPNjPfdo8bD--WDrkcz-lbtJ3P8Wugs/edit#heading=h.2g5p8k503yjk) part of the proposal.

# Background

This adds a new CRD, name Catalog, which allow the user to refer which catalog to register on the cluster. This would also bring a `tkn-catalog` binary (that could be taken into account by `tkn`) to interact with those CR.

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Catalog
metadata:
  name: upstream
spec:
  url: https://github.com/tektoncd/catalog
  revision: v0.7 # optional, default would be master or the default branch
  namespace: my-local-catalog
  update: # optional (defaults value to define)
    auto: true
    Interval: 1d # interval of auto-updates
---
apiVersion: tekton.dev/v1alpha1
kind: Catalog
metadata:
  name: openshift
spec:
  url: https://github.com/openshift/catalog
  version: v0.7 # optional, and semver (aka any v0.7.x would be used)
  update: # optional (defaults value to define)
    auto: true
    Interval: 1d
  Priority: 100
---
apiVersion: tekton.dev/v1alpha1
kind: Catalog
metadata:
  name: secret
spec:
  url: git@github.com:vdemeester/my-private-catalog.git
  update: # optional (defaults value to define)
    auto: true
    Interval: 1d
  secret: github-secret # to-be-defined (use creds-init as Task ?)
```

As this is *highly* experimental, we only wish to be a folder in the `tektoncd/experimental` (and we will see later on if it make sense to be on its own or not).

# Maintainers

@vdemeester and @sthaha would be the initial ones.
