### ISSUE TITLE
Installing Non Tekton Components through Tekton Operator

### ISSUE THREAD

**Issue by sm43** [tektoncd/community#750]
Operator provides multiple CRDs like `TektonPipeline`, `TektonTrigger` which on creation installs and manages the lifecycle of that respective component.

Example:
`TektonPipeline` -> install and manages `tektoncd/pipeline` component

There is a Top level CRD TektonConfig which manages other CRDs depending on the profile. So, after operator installation if you create TektonConfig with`all` profile on Kubernetes platform. It will install
- `TektonPipeline`
- `TektonTrigger`
- `TektonDashboard`

Recently, couple of more components were added which are not enabled by default
- TektonChain
- TektonHub

We support 2 platform at present using the [Extension Mechanism](https://github.com/tektoncd/operator/blob/fb21e8b7b4e9dc7beeb7b65bcb517a89fe193d27/pkg/reconciler/common/extensions.go)
- Kubernetes
- OpenShift
When a release is done, release yaml for both platform are published.

For OpenShift, instead of `TektonDashboard` we ship `TektonAddon` CRD
`TektonAddon` create additional resources for OpenShift platform only
- ClusterTasks
- Pipeline Templates
- ClusterTriggerBinding
- [Pipelines As Code](https://github.com/openshift-pipelines/pipelines-as-code)
- OpenShift Specific resources 
`TektonAddon` at present is not shipped with Kubernetes release yaml.

### Configuration
Currently, each CRD has fields in spec for configuration which are later propagated by reconciler to their configmaps and other resources.
As TektonConfig is a top level CRD, these are propagated from it to their respective CRDs.

Example:
```
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
   labels:
    operator.tekton.dev/release-version: 1.7.1
  name: config
spec:
  addon:
    enablePipelinesAsCode: true
    params:
    - name: clusterTasks
      value: "true"
    - name: pipelineTemplates
      value: "true"
    - name: communityClusterTasks
      value: "true"
  config: {}
  dashboard:
    readonly: false
  hub: {}
  params:
  - name: createRbacResource
    value: "true"
  pipeline:
    default-service-account: pipeline
    disable-affinity-assistant: true
    disable-creds-init: false
    enable-api-fields: stable
    enable-custom-tasks: false
    enable-tekton-oci-bundles: false
    params:
    - name: enableMetrics
      value: "true"
    require-git-ssh-secret-known-hosts: false
    running-in-environment-with-injected-sidecars: true
    scope-when-expressions-to-task: false
  profile: all
  pruner:
    keep: 100
    resources:
    - pipelinerun
    schedule: 0 8 * * *
  targetNamespace: openshift-pipelines
  trigger:
    default-service-account: pipeline
    enable-api-fields: stable
```

Platform specific configurations are passed through params, for example
```
    params:
    - name: enableMetrics
      value: "true"
```
This is passed as param on OpenShift so that it will not appear on Kubernetes platform. But this makes the UX inconsistent. [Issue](https://github.com/tektoncd/operator/issues/759) 

#### Need Improvements:

- [Pipelines As Code](https://github.com/openshift-pipelines/pipelines-as-code) which is a non-tekton project is currently installed as an Addon but as it is getting bigger, it requires its own CRD and reconciler to manage its installation and lifecycle.

### Proposal:
- We would like to add a Separate CRD and Reconciler to manage Pipelines As Code
So, if user create a CR for example PipelinesAsCode, it will be installed
As It’s a non Tekton project, we can be documented it is not supported by Tekton Community
It will be optional to install 
We can even decide to generate more "release.yaml", for example one with only tektoncd upstream component, etc..

- Adding a platform specific section in TektonConfig
  To make UX better, we would like to add a OpenShift Section
  TektonConfig will look as 
  ```
  apiVersion: operator.tekton.dev/v1alpha1
  kind: TektonConfig
  metadata:
     labels:
      operator.tekton.dev/release-version: 1.7.1
    name: config
  spec:
    trigger: {}
    dashboard: {}
    pipeline:
      default-service-account: pipeline
      disable-affinity-assistant: true
      disable-creds-init: false
      …
  
    openshift:
      enableMonitoring: true
    gcp: {}
  ```
  - In future we could have section for other cloud provider
  - On kubernetes, the CR will have openshift section mentioned but will not affect 
  - We could even "warn" the user if there is an openshift key present (that will be ignore) using the webhook
