### ISSUE TITLE
Add CRD `Queue` for tep 120 cancel existing pipelineruns

### ISSUE THREAD

**Issue by chengjoey** [tektoncd/community#951]
### Feature request
In [TEP-0120: Canceling Concurrent PipelineRuns](https://github.com/tektoncd/community/blob/main/teps/0120-canceling-concurrent-pipelineruns.md#tep-0120-canceling-concurrent-pipelineruns), people need to limit the number of concurrent runs of a set of `PipelineRun`, under the same set of pipelines, if there are new pipeline tasks, the previous ones should be cancelled, I think this process is the same as the first-in-first-out concept of the queue, maybe we can add a Queue Crd to allow users to declare a set of pipelineRun's simultaneous running window size.

here is a concept image I drew:
![Queue](https://user-images.githubusercontent.com/30427474/217019375-4970bbf4-4939-4768-b25c-76b7f0f454e0.png)

### Use case
```
apiVersion: tekton.dev/v1alpha1
kind: Queue
metadata:
  name: concurrency-queue
spec:
  pipelineConcurrency: 2
  strategy: Cancel

---
# Create three or more pipelineruns, and you can see that the pipelinerun that was run first
# is canceled until the number of concurrency in the binding queue is the same
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-with-queue-
  labels:
    # used to bind queue
    bind__queue: concurrency-queue
spec:
  pipelineSpec:
    tasks:
      - name: task1
        taskSpec:
          steps:
            - image: busybox
              script: |
                echo "hello"
                sleep 100
                echo "goodbye"
```

the above detailed Queue spc and user usage scenarios

I have written the initial code implementing in [pr 6112](https://github.com/tektoncd/pipeline/pull/6112), Maybe I should submit the code to [experimental](https://github.com/tektoncd/experimental) for experimental verification, but I have to modify the logic of the pipelinerun controller
